FROM java:openjdk-8u91-jdk
MAINTAINER ganeshatmail@gmail.com
EXPOSE 8080
CMD java -jar price-calculator-circuit-breaker-0.0.1-SNAPSHOT.jar
ADD build/price-calculator-circuit-breaker-0.0.1-SNAPSHOT.jar .